### ISSUE TITLE
Delete container to avoid name error while starting selenoid

### ISSUE THREAD

**Issue by SergeyPirogov** [iqoption/selenoid-docker#4]
If we have already running selenoid container instance and we want to run playbook there will be an error:

Error starting container blabla name already allocated by <container hash>

Now the solution is either to remove that container manually or add pre-task to the playbook.
How about adding the task *delete old selenoid container for the role*?

**Comment by arslanbekov** [comment]
Hi Sergey, thanks for the remark, we will add removal or check.
